name: conchayoro-pipeline
on:
  push:
    branches: [main]
    
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: us-east-1
  PROJECT_NAME: conchayoro
  MODULE_NAME: backend
  TAG: latest
  STACK_NAME: "64bit Amazon Linux 2 v3.5.7 running Docker"  
  SERVICE_ROLE: LabRole
  INSTANCE_PROFILE: LabInstanceProfile
  KEY_NAME: vockey
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      #- run: aws ecr create-repository --repository-name $PROJECT_NAME/$MODULE_NAME
      - run: docker build -t $PROJECT_NAME/$MODULE_NAME $MODULE_NAME/.
      - run: docker tag $PROJECT_NAME/$MODULE_NAME:$TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$PROJECT_NAME/$MODULE_NAME:$TAG
      - run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - run: docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$PROJECT_NAME/$MODULE_NAME:$TAG
      - uses: actions/upload-artifact@v3
        with:
          name: ebconfig
          path: | 
              backend/.elasticbeanstalk/config.yml
              backend/Dockerrun.aws.json
      
  deploy:
    runs-on: ubuntu-latest
    needs: build   
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ebconfig
          path: .
      - run: |
          sed -i='' "s/<AWS_ACCOUNT_ID>/$AWS_ACCOUNT_ID/" Dockerrun.aws.json
          sed -i='' "s/<PROJECT_NAME>/$PROJECT_NAME/" Dockerrun.aws.json
          sed -i='' "s/<MODULE_NAME>/$MODULE_NAME/" Dockerrun.aws.json
          sed -i='' "s/<TAG>/$TAG/" Dockerrun.aws.json
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install awsebcli      
      - run: |           
           eb deploy --verbose
